services:
  - type: web
    name: santa-rita-backend
    runtime: node
    buildCommand: npm install && npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: santa-rita-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://igrejasantaritaourofino.vercel.app
      - key: JWT_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: BACKEND_URL
        value: https://santa-rita-backend.onrender.com

databases:
  - name: santa-rita-db
    databaseName: santa_rita_db
    user: santa_rita_user